### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by ghost** [pog102/steam-tiers#1]
hey, it would be cool to add a pop-up which will trigger when u hover for a few seconds on a game image, which would display a small text with the name of the game on the top of the image (sometimes when the library is big u tend to not remember the name of the game just by looking at the image, also not all images have the game name on it)

**Comment by pog102** [comment]
![image](https://github.com/user-attachments/assets/a5011c89-3c63-46ee-8600-a8ab5260aafd)
Hovering works and added the names for unloaded images too.

**Comment by ghost** [comment]
Looks fire, love it :)
