### ISSUE TITLE
Some games do not get added

### ISSUE THREAD

**Issue by ghost** [pog102/steam-tiers#2]
While clicking on steam icon some games do not get added (their images), for example Sponge Bob: Cosmic Shake, Celeste, Jaded and so on. Also some games got added as images, but the images are broken, those are not loading.
![image](https://github.com/user-attachments/assets/0df11bfa-3f80-4ce9-b3b6-7de575c3793d)

**Comment by pog102** [comment]
Odd , I do own Celeste and it shows in the image list, maybe there's a hidden cap for the api that I'm unaware of.

**Comment by pog102** [comment]
Ye my bad, I made it only filter played games (>0 min). Now it should show all.

**Comment by ghost** [comment]
Nice, works fine but it seems that it doesnt load the images for the games that are not on steam shop anymore
![ytyt](https://github.com/user-attachments/assets/8c281341-4297-4e58-97f4-371dd8e3e13c)
but i guess u cant do anything about it
